<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "custom_content_element"
 *
 * Auto generated by Extension Builder 2016-07-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Custom Content Element',
	'description' => 'A skeleton for a custom content element based on fluid styled content',
	'category' => 'plugin',
	'author' => 'Michael Hitzler',
	'author_email' => 'michael.hitzler@paravista.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.3.0',
	'constraints' => [
		'depends' => [
			'typo3' => '8.7.0-9.5.99',
        ],
		'conflicts' => [
        ],
		'suggests' => [
        ],
    ],
];